import Head from 'next/head'
import Apresentation from '../components/apresentation'
import Section2 from '../components/section2'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting  from '../public/consulting.png'
import Image from "next/image"
import { BsFillMoonStarsFill } from "react-icons/bs";
import Section3 from '../components/section3'
import { useState } from "react"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sakuma Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 dark:bg-gray-900'>
        <section className='min-h-screen'>
        <nav className="py-10 mb-12 flex justify-between">
        <h1 className="text-xl font-burtons">scriptC0ffex</h1>
        <ul className="flex items-center">
          <li>
            <BsFillMoonStarsFill onClick={() => {
              setDarkMode(!darkMode)
              console.log(darkMode)
            }  
          } 
          className="cursor-pointer text-2xl" />
          </li>
          <li>
            <a
              className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
              href="#"
            >
              Resume
            </a>
          </li>
        </ul>
      </nav>
          <Apresentation/>
        </section>
          <Section2/>
        <section className="py-10">
          <Section3/>
        </section>
      </main>
      </div>
    </>
  )
}
