import Head from 'next/head'
import { AiFillLinkedin , AiFillGithub } from 'react-icons/ai'
import Apresentation from '../components/apresentation'
import Nav from '../components/nav'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sakuma Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <Nav/>
          <Apresentation/>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='mt-20'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum reiciendis modi itaque illo ipsum voluptas dolores numquam optio nulla deserunt velit, reprehenderit nihil exercitationem aspernatur obcaecati explicabo architecto aperiam unde.
            </p>
          </div>
        </section>
      </main>
    </>
  )
}
