import Head from 'next/head'
import Apresentation from '../components/apresentation'
import Nav from '../components/nav'
import Section2 from '../components/section2'
export default function Home() {
  return (
    <>
      <Head>
        <title>Sakuma Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <Nav/>
          <Apresentation/>
        </section>
          <Section2 />
        <section>
          
        </section>
      </main>
    </>
  )
}
